# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f727f77745028b3cc3dd07358e80cf4e"
name = "MergeCart"
application_url = "https://conjunction-memphis-analyses-teachers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy,write_products,write_cart_transforms"

[auth]
redirect_urls = [ "https://conjunction-memphis-analyses-teachers.trycloudflare.com/api/auth" ]

[app_proxy]
url = "/api"
prefix = "apps"
subpath = "api"

[[extensions]]
name = "bundle-cart-transform"
handle = "bundle-cart-transform"
type = "function"